[package]
name = "yubirs"
version = "0.2.0"
authors = ["Axel Rasmussen <axel.rasmussen1@gmail.com>"]
description = "A YubiKey OTP validation library"
homepage = "https://github.com/CmdrMoozy/yubirs"
repository = "https://github.com/CmdrMoozy/yubirs"
license = "Apache-2.0"

[dependencies]
bdrck = "0.6"
chrono = "0.4"
curl = "0.4"
data-encoding = "2.1"
error-chain = "0.11"
isatty = "0.1"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
openssl = "~0.10.4"
pcsc-sys = "1.0"
rand = "0.4"
regex = "0.2"
rpassword = "2.0"
