[package]
name = "yubirs"
version = "0.1.0"
authors = ["Axel Rasmussen <axel.rasmussen1@gmail.com>"]
description = "A YubiKey OTP validation library"
homepage = "https://github.com/CmdrMoozy/yubirs"
repository = "https://github.com/CmdrMoozy/yubirs"
license = "Apache-2.0"

[dependencies]
chrono = "0.4"
curl = "0.4"
data-encoding = "1.2"
error-chain = "0.11"
lazy_static = "0.2"
regex = "0.2"
rpassword = "1.0"
rust-crypto = "0.2"
sodiumoxide = "0.0.15"
